resources:
- github.com/kuadrant/kuadrant-dns-operator/config/default?ref=unified_kuadrant 

patches:
  - path: deployment_patch.yaml
    target:
      kind: Deployment
      name: kuadrant-dns-operator-controller-manager
